### ISSUE TITLE
Filter error?

### ISSUE THREAD

**Issue by usctzen** [irahorecka/pycraigslist#2]
Using the test code below, it seems that the filter options isn't working properly. If i run the code, all type of bikes show in the results.

```
import pycraigslist

bike_filters = {
    'posted_today': True,
    'bundle_duplicates': True,
    'make': 'Harley',
    'model': 'Softail'
}

bikes = pycraigslist.forsale.mca(site='miami', area='brw', filters=bike_filters)

for bike in bikes.search(limit=5):
    print(bike)
```

**Comment by usctzen** [comment]
Just tried to bypass the "filters" option using the code below and I still don't get the correct results.

```
bikes = pycraigslist.forsale.mca(
    site='miami', area='brw', make='Harley', model='Softail'
)
```

**Comment by irahorecka** [comment]
Thanks for catching this - I patched the issue and will conduct testing. I'll notify you when this patch is released to PyPI

**Comment by usctzen** [comment]
Glad I could help.

**Comment by irahorecka** [comment]
Hey Marc, I released the latest version that should address this issue. Let me know if this persists.
Still in the works for issue #1.

**Comment by usctzen** [comment]
Ira,
Still getting other bikes than the one searched. Some filters seem to work but not the "model" and "make" at least.

**Comment by usctzen** [comment]
Ira,

My mistake. "make" and "model" are in the result. They do not exist in the filter. The `.getfilters()` returns a "make_model" thus the confusion. When using the proper filter, it works well.

Thanks

```
import pycraigslist

bike_filters = {
    'search_titles': True,
    'posted_today': False,
    'bundle_duplicates': True,
    'make_model': 'Harley Ultra',
    'max_price': 5000
}

bikes = pycraigslist.forsale.mca(site='miami', area='brw', filters=bike_filters)

for bike in bikes.search(limit=5):
    print(bike)
```

**Comment by irahorecka** [comment]
Great, thanks again, Marc - I appreciate your contributions. I'll close this issue.
